---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: ebs-dynamic-pvc
          mountPath: /usr/share/nginx/html

  volumes:
    - name: ebs-dynamic-pvc
      persistentVolumeClaim:
        claimName: ebs-dynamic-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP